### ISSUE TITLE
Binding Precedence is Bound data before Old input when old == ''

### ISSUE THREAD

**Issue by Polfo** [glhd/aire#34] opened 2019-09-12 13:08 UTC
**Describe the bug**
When I edit/update data, and the form data does not pass validation, then the bound data is displayed instead of the old input.

**Have you published the Aire config file?**
No

**Have you added custom Aire views?**
No

**What version does this affect?**
- Laravel Version: 6.0.3
- Aire Version: 1.7.1
- Aire Bootstrap Version: 1.0.0-beta.4

**To Reproduce**
1. function edit() in controller returns view containing model data e.g. 1234
2. user empties the field
3. user pushes save button
4 function update() in controller runs `$request->validate($this->rules)` where rule is `required` and returns html with validation error
5 user sees 1234

**Expected behavior**
user sees his input and the reason why it is not valid: an empty field

**Comment by inxilpro** [comment] 2019-10-05 00:17
Sorry it took me so long to respond. At first I wasn't able to reproduce the issue, but it occurred to me that this likely is related to the `ConvertEmptyStringsToNull` middleware. Can you confirm that you're using that middleware? And if you remove that from your `Http\Kernel::$middleware` configuration, does it work as expected?

This is actually an issue with `\Illuminate\Session\Store::hasOldInput` which will return false if the old input value is `null`, which is exactly what the `ConvertEmptyStringsToNull` middleware does. 

I'm honestly not entirely sure how best to approach this.  We could potentially implement our own check by doing something like `Arr::exists(Session::get('_old_input', []), $key)`, but that would be a little brittle. I'm going to dig around a bit more and see if this can be solved at the framework level without introducing any unintended backwards-compatibility breaks.

**Comment by inxilpro** [comment] 2020-12-10 20:59
This was fixed in #42

**Closed by inxilpro** 2020-12-10 20:59 UTC
Labels: bug
